[OpenSimAI]
    ;; Enable / Disable the OpenSim AI Module.
    Enabled = true

    ;; Set the OpenSim AI Module to Public (false) or Private (true) mode.
    IsPrivate = true

    ;; Set your OpenRouter API key: "sk-or-v1-xxxxxYOUR_API_KEYxxxxx"
    ApiKey = ""
    
    ;; OpenRouter endpoint URL
    ApiUrl = "https://openrouter.ai/api/v1/chat/completions"
    
    ;; Set the free AI model to use. Default: "openrouter/free"
	;; More info : https://openrouter.ai/openrouter/free
	;; Free models : https://openrouter.ai/models?q=free
    ModelName = "openrouter/free"
    
    ;; Set the paid fallback model or leave empty.
	;; Recommanded : "deepseek/deepseek-v4-flash"
	;; More info : https://openrouter.ai/deepseek/deepseek-v4-flash
    FallbackModelName = ""
    
    ;; Enable / Disable the monetization: free (false) / paid (true)
    EnableMonetization = false
	
	;; Your UUID or the banker UUID.
	BankerUUID = ""

    ;; If the monetization is enabled (true), set the price per request
    PricePerRequest = 1
	